// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IAntDesignArrowLeftOutlined: typeof import('~icons/ant-design/arrow-left-outlined')['default']
    IAntDesignCalendarOutlined: typeof import('~icons/ant-design/calendar-outlined')['default']
    IAntDesignCommentOutlined: typeof import('~icons/ant-design/comment-outlined')['default']
    IAntDesignHeartOutlined: typeof import('~icons/ant-design/heart-outlined')['default']
    IAntDesignRetweetOutlined: typeof import('~icons/ant-design/retweet-outlined')['default']
    IAntDesignShareAltOutlined: typeof import('~icons/ant-design/share-alt-outlined')['default']
    IFa6SolidPlus: typeof import('~icons/fa6-solid/plus')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiX: typeof import('~icons/mdi/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
